- id: 0
  type: admin
  name: Administrator Role
- id: 1
  type: contract
  name: Contracting Officer
- id: 2
  type: manager
  name: Manager
- id: 3
  type: api_manager
  name: ApiManager
- id: 4
  type: recruit
  name: recruit
