development:
  adapter: mysql2
  encoding: utf8
  database: eobackbone_development
  pool: 5
  timeout: 5000
  username: root
  password:
  collation: utf8_bin

test:
  adapter: mysql2
  encoding: utf8
  database: eobackbone_test
  pool: 5
  timeout: 5000
  username: root
  password:
  collation: utf8_bin

production:
  adapter: mysql2
  encoding: utf8
  database: eobackbone
  pool: 5
  timeout: 5000
  username: root
  password:
  collation: utf8_bin

